### ISSUE TITLE
Clicking on Add This Question has stopped working on math.stackexchange

### ISSUE THREAD

**Issue by RossMillikan** [ultimatedelman/stackstalker#1]
When I click on Add This Question I get the rotating wait cursor.  After a while it stops, but the question is not added to my list.  I usually use this on math.stackexchange.  It does work on stackoverflow.  I don't know what version of Chrome I am using, but it is set for auto updates.  I tried restarting Chrome, then restarting the computer without success.  Windows 10.

**Comment by ultimatedelman** [comment]
Interesting. They must have just switched to https:// instead of http://.
I'll have to fix this. Thanks for posting!

**Comment by ultimatedelman** [comment]
Yeah it looks like any site that is using SSL is broken. Is an easy fix. I'll get to it tonight if I can.

**Comment by ultimatedelman** [comment]
Updated and published. Give it a little bit. Once you see 3.0.2 as your version, it means you're updated! Thanks for the report.

**Comment by RossMillikan** [comment]
Success.  Thanks 

    On Friday, May 5, 2017 10:09 AM, Jason Edelman <notifications@github.com> wrote:
 

 Updated and published. Give it a little bit. Once you see 3.0.2 as your version, it means you're updated! Thanks for the report.—

**Comment by ultimatedelman** [comment]
No problem. Feel free to leave a review in the chrome extension store ;)
